Repository spring-projects-experimental/spring-boot-migrator, pull requests merged in 2023-06, with the labels that each got.

#802 Commented Out and added TODO for now
  docs/reference/user-documentation.adoc
Labels: type: bug, type: documentation

#806 refactor: Rename parameter for methods to be more cohesive
  components/sbm-core/src/main/java/org/springframework/sbm/java/api/ProjectJavaSources.java
  components/sbm-core/src/main/java/org/springframework/sbm/java/impl/ProjectJavaSourcesImpl.java
  components/sbm-core/src/main/java/org/springframework/sbm/java/migration/actions/ReplaceTypeAction.java
  components/sbm-core/src/test/java/org/springframework/sbm/java/migration/actions/ReplaceTypeActionTest.java
  components/sbm-recipes-jee-to-boot/src/main/java/org/springframework/sbm/jee/jaxrs/MigrateJaxRsRecipe.java
  components/sbm-recipes-jee-to-boot/src/main/resources/recipes/migrate-stateless-ejb.yaml
  components/sbm-recipes-jee-to-boot/src/test/java/org/springframework/sbm/jee/ejb/recipes/MigrateStatelessEjbRecipeTest.java
Labels: type: refactoring

#810 cleanup: Clean imports
  components/sbm-core/src/main/java/org/springframework/sbm/engine/recipe/Recipe.java
Labels: type: cleanup

#811 doc: Add FIXME
  components/sbm-core/src/main/java/org/springframework/sbm/engine/recipe/RewriteRecipeRunner.java
Labels: type: documentation

#813 clean: Formatting and replace with text block
  components/sbm-recipes-boot-upgrade/src/test/java/org/springframework/sbm/boot/upgrade_24_25/recipes/Boot_24_25_UpdateDependenciesRecipeTest.java
Labels: type: cleanup

#816 815 remove emojis from cli
  applications/spring-shell/src/main/java/org/springframework/sbm/shell/RecipeRenderer.java
  applications/spring-shell/src/test/java/org/springframework/sbm/shell/RecipeRendererTest.java
  components/sbm-core/src/main/java/org/springframework/sbm/engine/context/ProjectContext.java
Labels: Shell, type: cleanup

#818 Apply recipes by number
  applications/spring-shell/src/main/java/org/springframework/sbm/shell/ApplicableRecipesListHolder.java
  applications/spring-shell/src/main/java/org/springframework/sbm/shell/ApplyShellCommand.java
  applications/spring-shell/src/main/java/org/springframework/sbm/shell/RecipeRenderer.java
  applications/spring-shell/src/main/java/org/springframework/sbm/shell/ScanShellCommand.java
  applications/spring-shell/src/test/java/org/springframework/sbm/shell/RecipeRendererTest.java
  components/sbm-core/src/main/java/org/springframework/sbm/engine/commands/ApplyCommand.java
Labels: type: enhancement, Shell

#821 Remove CLI colors
  applications/spring-shell/src/main/java/org/springframework/sbm/shell/ApplyCommandRenderer.java
  applications/spring-shell/src/main/java/org/springframework/sbm/shell/ApplyShellCommand.java
  applications/spring-shell/src/main/java/org/springframework/sbm/shell/PreconditionVerificationRenderer.java
  applications/spring-shell/src/main/java/org/springframework/sbm/shell/ScanCommandHeaderRenderer.java
  applications/spring-shell/src/test/java/org/springframework/sbm/shell/ApplyRecipeCommandHeaderRendererTest.java
  applications/spring-shell/src/test/java/org/springframework/sbm/shell/PreconditionVerificationRendererTest.java
Labels: Shell, type: cleanup

#822 Fix applicable recipe list holder
  applications/spring-shell/src/main/java/org/springframework/sbm/shell/ApplyShellCommand.java
  applications/spring-shell/src/main/java/org/springframework/sbm/shell/ScanShellCommand.java
  applications/spring-shell/src/test/java/org/springframework/sbm/shell/ScanShellCommandTest.java
  applications/spring-shell/src/test/java/org/springframework/sbm/shell/ScanShellCommandWithWindowsPathTest.java
  components/sbm-core/src/main/java/org/springframework/sbm/engine/commands/ApplicableRecipeListCommand.java
  components/sbm-core/src/main/java/org/springframework/sbm/engine/recipe/ApplicableRecipesListHolder.java
  components/sbm-core/src/main/java/org/springframework/sbm/java/impl/RewriteJavaParser.java
Labels: type: bug
