Repository spring-projects-experimental/spring-boot-migrator, pull requests merged in 2023-10, with the labels that each got.

#957 Fix #942 path issues on windows machines
  applications/spring-boot-upgrade/src/main/java/org/springframework/sbm/SpringBootMigratorRunner.java
  components/sbm-core/src/main/java/org/springframework/sbm/project/parser/MavenProjectParser.java
  components/sbm-utils/src/main/java/org/springframework/sbm/utils/LinuxWindowsPathUnifier.java
Labels: type: bug

#967 Remove missing recipe
  components/sbm-recipes-boot-upgrade/src/main/resources/recipes/27_30/report/sbu30-report.yaml
Labels: type: bug

#966 Fix jpa recipe with persistence.xml in test resources
  applications/spring-shell/src/test/java/org/springframework/sbm/IntegrationTestBaseClass.java
  applications/spring-shell/src/test/resources/testcode/project-with-persistence-xml-in-test-resources/pom.xml
  applications/spring-shell/src/test/resources/testcode/project-with-persistence-xml-in-test-resources/src/main/java/.keep
  applications/spring-shell/src/test/resources/testcode/project-with-persistence-xml-in-test-resources/src/main/resources/META-INF/persistence.xml
  applications/spring-shell/src/test/resources/testcode/project-with-persistence-xml-in-test-resources/src/test/resources/META-INF/persistence.xml
  components/sbm-core/src/main/java/org/springframework/sbm/project/resource/GenericTypeFilter.java
  components/sbm-recipes-jee-to-boot/src/main/java/org/springframework/sbm/jee/jpa/actions/MigrateEclipseLinkToSpringBoot.java
  components/sbm-recipes-jee-to-boot/src/main/java/org/springframework/sbm/jee/jpa/actions/MigratePersistenceXmlToApplicationPropertiesAction.java
  components/sbm-recipes-jee-to-boot/src/test/java/org/springframework/sbm/jee/jpa/actions/PersistenceXmlToSpringBootApplicationPropertiesActionTest.java
  components/sbm-support-jee/src/main/java/org/springframework/sbm/jee/jpa/filter/PersistenceXmlResourceFilter.java
Labels: type: bug

#972 Organize imports
  sbm-support-rewrite/src/main/java/org/springframework/sbm/boot/autoconfigure/ParserPropertiesPostProcessor.java
  sbm-support-rewrite/src/main/java/org/springframework/sbm/boot/autoconfigure/ScopeConfiguration.java
  sbm-support-rewrite/src/main/java/org/springframework/sbm/parsers/MavenProject.java
  sbm-support-rewrite/src/main/java/org/springframework/sbm/parsers/ModuleParser.java
  sbm-support-rewrite/src/main/java/org/springframework/sbm/parsers/ParserContext.java
  sbm-support-rewrite/src/main/java/org/springframework/sbm/parsers/ParserProperties.java
  sbm-support-rewrite/src/main/java/org/springframework/sbm/parsers/ProjectScanner.java
  sbm-support-rewrite/src/main/java/org/springframework/sbm/parsers/RewriteMavenArtifactDownloader.java
  sbm-support-rewrite/src/main/java/org/springframework/sbm/parsers/RewriteParserConfiguration.java
  sbm-support-rewrite/src/main/java/org/springframework/sbm/parsers/RewriteProjectParser.java
  sbm-support-rewrite/src/main/java/org/springframework/sbm/parsers/RewriteResourceParser.java
  sbm-support-rewrite/src/main/java/org/springframework/sbm/parsers/SourceFileParser.java
  sbm-support-rewrite/src/main/java/org/springframework/sbm/parsers/StyleDetector.java
  sbm-support-rewrite/src/main/java/org/springframework/sbm/parsers/events/StartedParsingResourceEvent.java
  sbm-support-rewrite/src/main/java/org/springframework/sbm/parsers/maven/BuildFileParser.java
  sbm-support-rewrite/src/main/java/org/springframework/sbm/parsers/maven/MavenModelReader.java
  sbm-support-rewrite/src/main/java/org/springframework/sbm/parsers/maven/MavenPasswordDecrypter.java
  sbm-support-rewrite/src/main/java/org/springframework/sbm/parsers/maven/MavenProvenanceMarkerFactory.java
  sbm-support-rewrite/src/main/java/org/springframework/sbm/parsers/maven/ProvenanceMarkerFactory.java
  sbm-support-rewrite/src/main/java/org/springframework/sbm/project/RewriteSourceFileWrapper.java
  sbm-support-rewrite/src/main/java/org/springframework/sbm/project/resource/ProjectResourceSetSerializer.java
  sbm-support-rewrite/src/main/java/org/springframework/sbm/project/resource/RewriteMigrationResultMerger.java
  sbm-support-rewrite/src/main/java/org/springframework/sbm/project/resource/SbmApplicationProperties.java
  sbm-support-rewrite/src/main/java/org/springframework/sbm/project/resource/finder/AbsolutePathResourcesFinder.java
  sbm-support-rewrite/src/main/java/org/springframework/sbm/project/resource/finder/GenericTypeFinder.java
  sbm-support-rewrite/src/main/java/org/springframework/sbm/project/resource/finder/GenericTypeListFinder.java
  sbm-support-rewrite/src/main/java/org/springframework/sbm/project/resource/finder/PathPatternMatchingProjectResourceFinder.java
  sbm-support-rewrite/src/main/java/org/springframework/sbm/project/resource/finder/RewriteSourceFileHolderListFinder.java
  sbm-support-rewrite/src/main/java/org/springframework/sbm/recipes/RewriteRecipeDiscovery.java
  sbm-support-rewrite/src/main/java/org/springframework/sbm/utils/OsAgnosticPathMatcher.java
  sbm-support-rewrite/src/test/java/io/example/recipes/AnotherDummyRecipe.java
  sbm-support-rewrite/src/test/java/org/openrewrite/maven/CalculateClasspathTest.java
  sbm-support-rewrite/src/test/java/org/openrewrite/maven/MavenParserTest.java
  sbm-support-rewrite/src/test/java/org/springframework/sbm/parsers/BuildFileParserTest.java
  sbm-support-rewrite/src/test/java/org/springframework/sbm/parsers/ParserEventPublicationIntegrationTest.java
  sbm-support-rewrite/src/test/java/org/springframework/sbm/parsers/maven/MavenConfigFileParserTest.java
  sbm-support-rewrite/src/test/java/org/springframework/sbm/parsers/maven/MavenExecutionRequestFactory.java
  sbm-support-rewrite/src/test/java/org/springframework/sbm/parsers/maven/MavenPomCacheTest.java
  sbm-support-rewrite/src/test/java/org/springframework/sbm/parsers/maven/MavenProjectAnalyzerTest.java
  sbm-support-rewrite/src/test/java/org/springframework/sbm/parsers/maven/ProvenanceMarkerFactoryTest.java
  sbm-support-rewrite/src/test/java/org/springframework/sbm/parsers/maven/RewriteMavenProjectParser.java
  sbm-support-rewrite/src/test/java/org/springframework/sbm/parsers/maven/RewriteMavenProjectParserTest.java
  sbm-support-rewrite/src/test/java/org/springframework/sbm/parsers/maven/SbmTestConfiguration.java
  sbm-support-rewrite/src/test/java/org/springframework/sbm/test/util/DummyResource.java
Labels: type: cleanup, in: sbm-support-rewrite, revamp

#976 Provide test to prove bug in #975
  sbm-support-rewrite/src/test/java/org/springframework/sbm/parsers/CompareParserRecipeRunTest.java
  sbm-support-rewrite/testcode/maven-projects/parser-recipe-run/pom.xml
  sbm-support-rewrite/testcode/maven-projects/parser-recipe-run/src/main/java/com/example/app/AppApplication.java
  sbm-support-rewrite/testcode/maven-projects/parser-recipe-run/src/main/java/com/example/app/My.java
  sbm-support-rewrite/testcode/maven-projects/parser-recipe-run/src/main/java/com/example/app/MyRepository.java
Labels: type: test, in: sbm-support-rewrite, revamp

#978 RecipeRun differs between parsers
  sbm-support-rewrite/src/main/java/org/springframework/sbm/parsers/ModuleParser.java
  sbm-support-rewrite/src/test/java/org/springframework/sbm/parsers/CompareParserRecipeRunTest.java
  sbm-support-rewrite/src/test/java/org/springframework/sbm/parsers/ParserPropertiesTest.java
Labels: type: bug, in: sbm-support-rewrite, revamp

#965 Windows path fixes
  .gitignore
  components/sbm-core/src/main/java/org/springframework/sbm/build/migration/MavenPomCacheProvider.java
  components/sbm-core/src/main/java/org/springframework/sbm/common/filter/PathPatternMatchingProjectResourceFinder.java
  components/sbm-core/src/main/java/org/springframework/sbm/common/util/OsAgnosticPathMatcher.java
  components/sbm-core/src/main/java/org/springframework/sbm/engine/context/ProjectContext.java
  components/sbm-core/src/main/java/org/springframework/sbm/engine/git/GitSupport.java
  components/sbm-core/src/main/java/org/springframework/sbm/engine/precondition/JavaSourceDirExistsPreconditionCheck.java
  components/sbm-core/src/main/java/org/springframework/sbm/project/parser/MavenProjectParser.java
  components/sbm-core/src/main/java/org/springframework/sbm/project/parser/PathScanner.java
  components/sbm-core/src/main/java/org/springframework/sbm/project/resource/RewriteSourceFileHolder.java
  components/sbm-core/src/test/java/org/springframework/sbm/build/api/Module_searchMainJava_Test.java
  components/sbm-core/src/test/java/org/springframework/sbm/build/api/Module_searchMainResources_Test.java
  components/sbm-core/src/test/java/org/springframework/sbm/build/api/Module_searchTestJava_Test.java
  components/sbm-core/src/test/java/org/springframework/sbm/build/api/Module_searchTestResources_Test.java
  components/sbm-core/src/test/java/org/springframework/sbm/build/impl/MavenSettingsInitializerTest.java
  components/sbm-core/src/test/java/org/springframework/sbm/common/migration/actions/MoveFilesActionTest.java
  components/sbm-core/src/test/java/org/springframework/sbm/engine/git/GitSupportTest.java
  components/sbm-core/src/test/java/org/springframework/sbm/engine/precondition/PreconditionVerifierIntegrationTest.java
  components/sbm-core/src/test/java/org/springframework/sbm/project/TestDummyResource.java
  components/sbm-core/src/test/java/org/springframework/sbm/project/buildfile/AddDependencyTest.java
  components/sbm-core/src/test/java/org/springframework/sbm/project/resource/TestProjectContext.java
  components/sbm-core/src/test/java/org/springframework/sbm/test/SpringBeanProvider.java
  components/sbm-recipes-boot-upgrade/src/test/java/org/springframework/sbm/boot/upgrade_27_30/report/SpringBootUpgradeReportActionTest.java
  components/sbm-recipes-spring-framework/src/main/java/org/springframework/sbm/actions/spring/xml/include/ImportSpringXmlConfigAction.java
  components/sbm-recipes-spring-framework/src/main/java/org/springframework/sbm/project/resource/filter/XmlSpringBeanConfigurationFilter.java
  components/sbm-support-boot/src/main/java/org/springframework/sbm/boot/properties/SpringApplicationPropertiesPathMatcher.java
  components/sbm-utils/src/main/java/org/springframework/sbm/utils/LinuxWindowsPathUnifier.java
Labels: type: bug, type: refactoring
