Repository spring-projects-experimental/spring-boot-migrator, pull requests merged in 2023-02, with the labels that each got.

#706 Fix calculation of base package
  components/sbm-core/src/main/java/org/springframework/sbm/java/util/BasePackageCalculator.java
  components/sbm-core/src/test/java/org/springframework/sbm/build/impl/JavaSourceSetImplTest.java
  components/sbm-core/src/test/java/org/springframework/sbm/java/util/BasePackageCalculatorTest.java
Labels: type: enhancement, in: engine

#719 Update README.adoc :: Explain the difference between spring-boot-upgrade.jar & spring-boot-migrator.jar
  README.adoc
Labels: type: documentation

#728 Upgrade openrewrite 7.35.0
  components/openrewrite-spring-recipes/src/main/java/org/springframework/sbm/OrRecipesConfig.java
  components/openrewrite-spring-recipes/src/test/java/org/springframework/sbm/SpringBoot23To24MigrationTest.java
  components/recipe-test-support/src/main/java/org/springframework/sbm/test/ProjectContextFileSystemTestSupport.java
  components/recipe-test-support/src/main/java/org/springframework/sbm/test/RecipeTestSupport.java
  components/sbm-core/src/main/java/org/springframework/sbm/build/api/BuildFile.java
  components/sbm-core/src/main/java/org/springframework/sbm/build/api/SpringManagedDependencies.java
  components/sbm-core/src/main/java/org/springframework/sbm/build/impl/MavenBuildFileRefactoring.java
  components/sbm-core/src/main/java/org/springframework/sbm/build/impl/MavenBuildFileRefactoringFactory.java
  components/sbm-core/src/main/java/org/springframework/sbm/build/impl/OpenRewriteMavenBuildFile.java
  components/sbm-core/src/main/java/org/springframework/sbm/build/impl/OpenRewriteMavenPlugin.java
  components/sbm-core/src/main/java/org/springframework/sbm/build/impl/RewriteMavenArtifactDownloader.java
  components/sbm-core/src/main/java/org/springframework/sbm/build/migration/actions/AddDependenciesToApplicationModules.java
  components/sbm-core/src/main/java/org/springframework/sbm/build/migration/actions/AddMinimalPomXml.java
  components/sbm-core/src/main/java/org/springframework/sbm/build/resource/BuildFileResourceWrapper.java
  components/sbm-core/src/main/java/org/springframework/sbm/engine/commands/ScanCommand.java
  components/sbm-core/src/main/java/org/springframework/sbm/java/impl/DependenciesChangedEventHandler.java
  components/sbm-core/src/main/java/org/springframework/sbm/java/impl/OpenRewriteJavaSource.java
  components/sbm-core/src/main/java/org/springframework/sbm/java/migration/visitor/VisitorUtils.java
  components/sbm-core/src/main/java/org/springframework/sbm/openrewrite/RewriteExecutionContext.java
  components/sbm-core/src/main/java/org/springframework/sbm/project/parser/DependencyHelper.java
  components/sbm-core/src/main/java/org/springframework/sbm/project/parser/MavenProjectParser.java
  components/sbm-core/src/main/java/org/springframework/sbm/project/parser/ProjectContextInitializer.java
  components/sbm-core/src/main/java/org/springframework/sbm/project/parser/ResourceParser.java
  components/sbm-core/src/main/java/org/springframework/sbm/project/resource/RewriteSourceFileHolder.java
  components/sbm-core/src/main/java/org/springframework/sbm/properties/migration/recipes/AddProperty.java
  components/sbm-core/src/main/java/org/springframework/sbm/search/recipe/CommentJavaSearchResult.java
  components/sbm-core/src/test/java/org/springframework/sbm/build/impl/MavenSettingsInitializerTest.java
  components/sbm-core/src/test/java/org/springframework/sbm/build/migration/actions/AddMavenDependencyManagementActionTest.java
  components/sbm-core/src/test/java/org/springframework/sbm/build/migration/actions/RemoveManagedDependenciesTest.java
  components/sbm-core/src/test/java/org/springframework/sbm/java/impl/OpenRewriteMethodTest.java
  components/sbm-core/src/test/java/org/springframework/sbm/java/impl/OpenRewriteSearchAndCommentTest.java
  components/sbm-core/src/test/java/org/springframework/sbm/project/buildfile/AddDependencyTest.java
  components/sbm-core/src/test/java/org/springframework/sbm/project/buildfile/OpenRewriteMavenBuildFileTest.java
  components/sbm-core/src/test/java/org/springframework/sbm/project/parser/MavenProjectParserTest.java
  components/sbm-core/src/test/java/org/springframework/sbm/project/parser/ProjectContextInitializerTest.java
  components/sbm-core/src/test/java/org/springframework/sbm/project/resource/TestProjectContext.java
  components/sbm-openrewrite/src/main/java/org/openrewrite/maven/spring/UpgradeUnmanagedSpringProject.java
  components/sbm-openrewrite/src/test/java/org/openrewrite/maven/MavenParserTest.java
  components/sbm-openrewrite/src/test/java/org/openrewrite/maven/UpdateMavenModelTest.java
  components/sbm-openrewrite/src/test/java/org/springframework/sbm/openrewrite/maven/MavenParserTest.java
  components/sbm-openrewrite/src/test/java/org/springframework/sbm/support/openrewrite/api/MavenDependencyDownloadTest.java
  components/sbm-openrewrite/src/test/java/org/springframework/sbm/support/openrewrite/api/RemoveUnusedImportsTest.java
  components/sbm-openrewrite/src/test/java/org/springframework/sbm/support/openrewrite/api/UpgradeDependencyVersionTest.java
  components/sbm-openrewrite/src/test/java/org/springframework/sbm/support/openrewrite/java/CodeCommentTest.java
  components/sbm-openrewrite/src/test/java/org/springframework/sbm/support/openrewrite/java/MavenPomDownloaderTest.java
  components/sbm-recipes-boot-upgrade/src/test/java/org/springframework/sbm/boot/upgrade_27_30/checks/RedeclaredDependenciesFinderTest.java
  components/sbm-recipes-boot-upgrade/src/test/java/org/springframework/sbm/boot/upgrade_27_30/report/helper/UpgradeDepenenciesMigrationTest.java
  components/sbm-recipes-jee-to-boot/src/test/java/org/springframework/sbm/jee/jaxrs/actions/ConvertJaxRsAnnotationsTest.java
  components/sbm-support-boot/src/main/java/org/springframework/sbm/boot/cleanup/actions/RemoveRedundantMavenCompilerPluginProperties.java
  components/sbm-support-boot/src/test/java/org/springframework/sbm/boot/cleanup/actions/RemoveRedundantMavenCompilerPluginPropertiesTest.java
  components/sbm-support-boot/src/test/java/org/springframework/sbm/boot/common/recipes/InitializeSpringBootMigrationRecipeIntegrationTest.java
  components/sbm-support-boot/testcode/multi-module-simple/expected/module1/pom.xml
  pom.xml
Labels: type: dependency-upgrade
